# Generated by Django 4.2.6 on 2023-10-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=12, upload_to='products_image', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
